environments:
  - name: dev
    cluster:
      instanceType: t2.medium
      desiredCapacity: 1
      maxSize: 2
      keyName: skyland-tech-access
      sshAllow: 0.0.0.0/0
      imageId: ami-0c8d8877
service:
  name: muexample
  port: 80
  healthEndpoint: /index.html
  pathPatterns: 
  - /*
  pipeline:
    source:
      provider: GitHub
      repo: tmcelhattan/muexample
    build:
      image: aws/codebuild/eb-ruby-2.3-amazonlinux-64:2.1.6
    acceptance:
      image: aws/codebuild/eb-ruby-2.3-amazonlinux-64:2.1.6
      environment: dev
    production:
      environment: pims-prod
      disabled: true

templates:
  mu-vpc-dev:
    Resources:
      VPCPeeringConnection:
        Type: "AWS::EC2::VPCPeeringConnection"
        Properties: 
          PeerVpcId: vpc-d5451aac
          VpcId:
            Ref: VPC

